services:
  nginx:
    image: nginx:stable-alpine3.17-slim
    container_name: root_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config:/etc/nginx/conf.d
      - ./nginx/index.html:/usr/share/nginx/index.html
      - ./ssl/www:/var/www/certbot
      - ./ssl/conf:/etc/letsencrypt

networks:
  internalnet:
