version: "3"

services:
  nginx:
    image: nginx:1.25.3
    container_name: root_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./config:/etc/nginx/conf.d
      - ./index.html:/usr/share/nginx/index.html